[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/articles/*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Ensure SPA behavior for hash routing
[[redirects]]
  from = "/blogs"
  to = "/blogs.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Handle 404s by serving the appropriate page
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200